### ISSUE TITLE
OpenSSL issue

### ISSUE THREAD

**Issue by shubham8garg** [alon-albalak/TLiDB#4]
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2k-fips  26 Jan 2017. See: https://github.com/urllib3/urllib3/issues/2168

**Comment by alon-albalak** [comment]
Hey @shubham8garg can you try installing the requirements with urllib3 == 1.26.8

Please let me know if that fixes your issue

**Comment by alon-albalak** [comment]
I'll close this issue for now. Feel free to reopen if you need @shubham8garg

**Comment by shubham8garg** [comment]
Yes, I was able to make it work by switching to ubuntu. Had to change the package dependencies versions in setup.py.
Thanks for the help.
